name: Deploy to Production
    
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        env:
          working-directory: .
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}
      - name: Build with Gradle
        env:
          working-directory: .
        run: ./gradlew clean build
        working-directory: ${{ env.working-directory }}

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy Scripts
        run: cp ./scripts/*.sh ./deploy

      - name: Copy appspec
        run: cp appspec.yml ./deploy/

      - name: Make zip file
        run: zip -r ./github-actions-test.zip ./deploy

      - name: S3 Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 --acl private ./github-actions-test.zip s3://github-actions-codedeploy-test/

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name deploy-test-app \
          --deployment-group-name deploy-test-app-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=github-actions-codedeploy-test,bundleType=zip,key=github-actions-test.zip \
          --region ap-northeast-2
