name: Deploy to Production3
    
on:
  push:
    branches:
      - main
    
jobs:
  deploy:
    name: Build, Deploy to S3 bucket2
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        env:
          working-directory: .
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}
      - name: Build with Gradle
        env:
          working-directory: .
        run: ./gradlew build
        working-directory: ${{ env.working-directory }}
    
      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: github-actions-test3
          AWS_ACCESS_KEY_ID: '$AWS_IAM_MANAGER_KEY_ID'
          AWS_SECRET_ACCESS_KEY: '$AWS_IAM_MANAGER_SECRET_ACCESS_KEY'
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: 'dist'

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name github-actions-test-app --deployment-group-name github-actions-test-app-group --s3-location bucket=github-actions-test3,key=github-actions-test.zip,bundleType=zip
